version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: discord.js
    versions:
    - "> 11.4.2"
  - dependency-name: sequelize
    versions:
    - 6.5.0
    - 6.5.1
    - 6.6.1
  - dependency-name: enmap
    versions:
    - 5.8.4
  - dependency-name: sqlite3
    versions:
    - 5.0.1
